# This is a basic workflow to help you get started with Actions

name: Gitspatch

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      webhook_event_id:
        description: 'Event ID from Gitspatch'
        required: true
      webhook_event_payload:
          description: 'Original webhook payload as string'
          required: false


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Echo values
        run: |
          echo ${{ github.event.inputs.webhook_event_id }}
          echo ${{ github.event.inputs.webhook_event_payload }}
