# This is a basic workflow to help you get started with Actions

name: Gitspatch

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      webhook_event_id:
        description: 'Event ID from Gitspatch'
        required: true
      webhook_event_payload:
          description: 'Original webhook payload as string'
          required: false

permissions:
  contents: write
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Report Workflow Run
        id: workflow-run
        run: |
          # retrieve the ambient OIDC token
          resp=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=gitstpatch")
          oidc_token=$(jq -r '.value' <<< "${resp}")
          curl -X POST https://b06203f76217.ngrok.app/action/workflow-run -H "Authorization: Bearer ${oidc_token}" -d "{\"event_id\": \"${{ github.event.inputs.webhook_event_id }}\"}"
      - name: Echo values
        run: |
          echo ${{ github.event.inputs.webhook_event_id }}
          echo ${{ github.event.inputs.webhook_event_payload }}
